import json
monster = [{
    'stage': 1,
    'killed': 0,
    'pname': 'Green Snake',
    'name': '---Green Snake----',
    'level': 1,
    'experience': 0,
    'maxexperience': 2,
    'hp': 7,
    'strength': 1,
    'damage': 1,
    'armor': 1,
    'defense': 1,
    'hitrate': 15,
    'given': 0,
}, {
    'stage': 1,
    'killed': 0,
    'pname': 'Red Snake',
    'name': '----Red Snake-----',
    'level': -1,
    'experience': 0,
    'maxexperience': 2,
    'hp': 8,
    'strength': 1,
    'damage': 1,
    'armor': 1,
    'defense': 1,
    'hitrate': 20,
    'given': 1,
}, {
    'stage': 2,
    'killed': 0,
    'pname': 'Brown Bear',
    'name': '----Brown Bear----',
    'level': 3,
    'experience': 0,
    'maxexperience': 6,
    'hp': 21,
    'strength': 1,
    'damage': 3,
    'armor': 4,
    'defense': 20,
    'hitrate': 10,
    'given': 1,
}, {
    'stage': 2,
    'killed': 0,
    'pname': 'Black Bear',
    'name': '----Black Bear----',
    'level': -3,
    'experience': 0,
    'maxexperience': 6,
    'hp': 25,
    'strength': 2,
    'damage': 4,
    'armor': 4,
    'defense': 20,
    'hitrate': 20,
    'given': 2,
}, {
    'stage': 3,
    'killed': 0,
    'pname': 'Black Scopion',
    'name': '--Black Scopion---',
    'level': 5,
    'experience': 0,
    'maxexperience': 10,
    'hp': 35,
    'strength': 7,
    'damage': 6,
    'armor': 3,
    'defense': 10,
    'hitrate': 30,
    'given': 2,
}, {
    'stage': 3,
    'killed': 0,
    'pname': 'White Scopion',
    'name': '--White Scopion---',
    'level': -5,
    'experience': 0,
    'maxexperience': 10,
    'hp': 35,
    'strength': 7,
    'damage': 7,
    'armor': 4,
    'defense': 5,
    'hitrate': 40,
    'given': 3,
}, {
    'stage': 4,
    'killed': 0,
    'pname': 'Tailless Scopion',
    'name': '-Tailless Scopion-',
    'level': 10,
    'experience': 0,
    'maxexperience': 20,
    'hp': 100,
    'strength': 12,
    'damage': 13,
    'armor': 13,
    'defense': 20,
    'hitrate': 70,
    'given': 3,
}]
with open('monster.json', 'w') as outfile:
    json.dump(monster, outfile)